#!/bin/bash

if [ $# != 2 ]; then
    echo "usage: ourcontract-mkdll [CONTRACTS DIR] [CONTRACT]"
else
    if [ $# > 2 ] then
        gcc -fPIC -g -c -Wall $3 -o "$1/$2/code.o" "$1/$2/code.c"
    else
        gcc -fPIC -g -c -Wall -o "$1/$2/code.o" "$1/$2/code.c"
    fi
    gcc -shared -Wl,-soname,"$2/code.so" -o "$1/$2/code.so" "$1/$2/code.o"
    rm -f "$1/$2/code.o"
fi
